enabled: true
handle: jobrequest
name: 'Job Request'
settings:
  authUrl: 'https://fm.x2network.net/fmi/data/v2/databases/ausdone/sessions'
  host: null
  length: null
  password: 'A4R67YYi&r$'
  postUrl: null
  token: null
  username: fmapi
  webhook: 'https://fm.x2network.net/fmi/data/v2/databases/ausdone/layouts/requestwebhook/records'
sortOrder: 1
tokenId: null
type: craftyfm\craftformiefilemaker\WebhookFilemaker
