fieldLayouts:
  31abc72c-4073-4c80-84c8-b05105853ed2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: dd58ab46-98e0-418b-9e66-a05f5905e13f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7827286a-15cd-438c-a9e9-0f2e2398bcf5
        userCondition: null
handle: archive
hasTitleField: false
name: Archive
section: 610888e4-a1ea-4d98-acea-1a20d0e0f0d2 # Archive
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
