fieldLayouts:
  f156b76d-d5b4-43bc-96ac-4ba67484c615:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 423c945d-1cb7-4630-8703-f8eecfc49d85
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: eb32cbf9-8c3b-4bc5-b478-7efe71705091 # Matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cab02f57-1647-47fa-bc1c-0324b1ca0314
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9a9e8b8a-0c63-40fc-9d5d-e5cc41c682c1
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: b90c37e6-c4f9-471a-8a79-a3c5ddb40a77 # Matrix Section
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
