fieldLayouts:
  57c97a83-4ed5-4622-852d-b45da7620889:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f4702b0b-7cc6-4187-a69f-c1ee1784923b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5f284340-be3f-49a6-b18e-2bbbc297349d # Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5bf12b9c-07e6-419f-9c0b-80d260c9019a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 13f45510-7742-4453-a66d-32b723a73bc1 # Text Alignment
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8a42a66-ca5a-4728-84b3-ee707624bc9b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 21dc67de-a521-4df1-b30d-358dca6de497 # Top Logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16ade0dc-c2f4-44a3-8b85-8d53f308b24b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3f7dfdfa-b803-4947-b21d-4c152cebd1d1 # H1 Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44bfd4df-ebe3-42a6-bec2-55e753f1ce54
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d55b8f1b-c721-47d5-907a-a5b3b4f8c6b8 # H1 Heading Text Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 062a8528-428a-4326-9655-ba2f859ca9ef
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b51d9d86-2b0a-4190-bec1-c98257042834 # H3 Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82e5385f-e2b6-43a8-bc9d-f9efc1506f31
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 41940fba-349c-479b-9bc8-91a243d32a3c # H3 Text Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2289f7fe-9b93-4fbb-9ca1-9e60e8d3ac55
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0b0cab67-d09f-4537-8f25-e2d3eb67217e # Bottom Logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f0b741c8-20df-4165-a9a1-10af6abb43a1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7203d17b-1373-42e9-95c6-d513d1e8a806
        userCondition: null
handle: homeHeroBanner
hasTitleField: true
name: 'Home Hero Banner'
section: b21e8675-fc63-4b2e-b48d-16eb726f815a # Home Hero Banner
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
