fieldLayouts:
  c18a9bdc-e8fe-4e17-aa06-49a12c6677f1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            template: _relations
            type: craft\fieldlayoutelements\Template
            uid: 40500af5-2534-4b31-bdec-d74c556e5014
            userCondition: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 22c87dc7-c9b6-4686-b197-0c627da820e0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dbf3edd5-28da-4614-84d3-0841fbb8252b # Worker Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad0cf8f1-4e14-42cc-80d4-a5229d45bf99
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e1716f4e-7b80-4caa-a01a-f0c206f5b15f # Worker description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e786f1f5-0f86-4b10-a040-39b1ed187112
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 75903ba9-227c-4d7e-99aa-7f584aa8200c # Worker ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54d0e5fd-719c-4f7a-be51-32d25864aad7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 20a04498-465d-42e1-96e1-fa040f064a38 # Name first
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c0bcb4f-5ca5-4673-88a2-c63c1907fd88
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f7390550-7c31-47e0-ac43-41b97e72f1a7 # Name last
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4cd9f6f2-ad3b-44b6-a388-4f760fb4e21c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 76bbde13-e3fd-4a51-8ab2-db4bb0f7c043 # Name Full
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 921474b2-9771-4e55-92ce-64a23ae24d7c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 523b90ff-4ad6-4738-bb9a-21f596f1d8e6 # Cover image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08528049-136a-4a80-8fac-6a55b1b0c4e8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b4a0f245-6040-43c8-b4f3-236d895fd240 # Image gallery
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93dc9b39-86c9-4997-b7dc-fdb53100769f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 52e559fe-2524-4d45-91c8-7aefd69d07b4 # Hours
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fbd7d479-7cd4-4a7e-99b0-455513fb7c76
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 58855ca8-c890-4430-96a6-640139fb7d24 # Worker - experience text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 17cc4592-83ee-4370-b3bb-057904e1faec
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 40423bd5-222b-4e05-9db8-d6d3fb9a56e7 # Worker - formal training text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49fd4420-960e-4ede-810b-ad64aef353d1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 94209415-2a6c-469d-a232-ca8b86975199 # Worker - services offered text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf1fbf85-c375-497e-9f7d-727645d726f9
            userCondition: null
            warning: null
            width: 100
        name: Details
        uid: 392b32ee-768d-424c-b284-d7862dcb0022
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e7aed0e8-a5ac-45c1-9f54-942bd630b588 # LanguageSpoken
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a93484df-fd1a-4e59-8325-a7224217439c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5a898a8e-0b51-479e-a204-99fe7b0d28c9 # Gender
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f93b703-5623-4d6d-a086-893acd9932c1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1e24cdd8-9955-4209-8ac1-0f100d6182ed # Qualifications level
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 158a3248-32ae-4edf-9600-efc252e6d6bf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e58f1760-17c2-4aea-bd7a-c3eb8d9ede32 # Worker services
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9fe4ee59-29fa-4bac-94a3-1470e6aeea11
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 11372e41-b6d0-4f56-8ebc-dc3f30b43e28 # Worker Cert IV switch
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0aeeb5ba-b0f9-4dee-bc84-70ce7a75c179
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 04d7a610-a4fd-4563-a910-0f069dc05c49 # Worker drivers license switch
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4af0daa-dfd3-497d-9b7f-856dde9c770c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a711ddbd-6947-48bd-b820-f0f52d8b265c # Worker first aid switch
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6609376a-acf4-4f43-b86e-9a6401b4408a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ab5e9ab5-f6af-43a6-8d7c-605a3c6eccb2 # Worker meal prep switch
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 661738cd-826b-4292-be70-6038c1d083d9
            userCondition: null
            warning: null
            width: 100
        name: 'Search fields'
        uid: 88781f31-394c-4a49-abd4-b41a6ae2b5d6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 432d5465-eb64-499b-a874-86c84d5e1290 # Address line 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d83b7cc8-01d9-435e-b0ea-50f69c84ab8e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c28af183-86b2-49d2-92f9-fd6d75e26aa6 # Address line 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2fdb383d-19d9-4918-b16a-9e48c0a040a7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b776ceed-90fc-4ec5-b204-6d414157c00d # Address suburb
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 91c50d9b-ab8d-4a89-b59c-9f09d0a8f219
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0807e9f7-09b8-43cd-8470-a0f65eaf2baa # Address state
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44c4a63b-bfcd-46f2-a04e-4a2f1d714af1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 94f12f0a-8bfc-4664-b90f-26859d58663c # Address postcode
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f47333b-2d65-4890-b72f-7cec9bee5d12
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1cd59306-3a97-4446-8369-3d467bcdcab1 # Address country
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64830e6d-7b46-4f8b-b830-e876e65ce41c
            userCondition: null
            warning: null
            width: 100
        name: Address
        uid: 18ce4a69-ab2c-43ae-a6ba-9438b662bbbd
        userCondition: null
handle: worker
hasTitleField: true
name: Worker
section: 3e1051a2-12ef-44a2-a5d4-17c675b92c46 # Worker single
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
