fieldLayouts:
  6f91a9f3-9c18-426a-bad9-cf5cbd9582fa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cbba43b8-cc40-48cb-8ba1-4ebb7f9a0d3a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 16192c12-5e06-49c1-af4d-b952bafd9dc1
        userCondition: null
handle: workersSearch
hasTitleField: false
name: 'Workers Search'
section: bbae794d-848e-45ea-ab84-0edc0c470817 # Workers Search
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
