fieldLayouts:
  c18a9bdc-e8fe-4e17-aa06-49a12c6677f1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 22c87dc7-c9b6-4686-b197-0c627da820e0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dbf3edd5-28da-4614-84d3-0841fbb8252b # Worker Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad0cf8f1-4e14-42cc-80d4-a5229d45bf99
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 75903ba9-227c-4d7e-99aa-7f584aa8200c # Worker ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54d0e5fd-719c-4f7a-be51-32d25864aad7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5a2c72c6-d960-4c8d-bf6b-2efebc4313bc # Flag active
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7a67023b-a343-4926-8b88-e70a4e88f7cd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 20a04498-465d-42e1-96e1-fa040f064a38 # Name first
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c0bcb4f-5ca5-4673-88a2-c63c1907fd88
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f7390550-7c31-47e0-ac43-41b97e72f1a7 # Name last
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4cd9f6f2-ad3b-44b6-a388-4f760fb4e21c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 76bbde13-e3fd-4a51-8ab2-db4bb0f7c043 # Name Full
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 921474b2-9771-4e55-92ce-64a23ae24d7c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 432d5465-eb64-499b-a874-86c84d5e1290 # Address line 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d83b7cc8-01d9-435e-b0ea-50f69c84ab8e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c28af183-86b2-49d2-92f9-fd6d75e26aa6 # Address line 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2fdb383d-19d9-4918-b16a-9e48c0a040a7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b776ceed-90fc-4ec5-b204-6d414157c00d # Address suburb
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 91c50d9b-ab8d-4a89-b59c-9f09d0a8f219
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0807e9f7-09b8-43cd-8470-a0f65eaf2baa # Address state
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44c4a63b-bfcd-46f2-a04e-4a2f1d714af1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 94f12f0a-8bfc-4664-b90f-26859d58663c # Address postcode
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f47333b-2d65-4890-b72f-7cec9bee5d12
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1cd59306-3a97-4446-8369-3d467bcdcab1 # Address country
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64830e6d-7b46-4f8b-b830-e876e65ce41c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 523b90ff-4ad6-4738-bb9a-21f596f1d8e6 # photo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08528049-136a-4a80-8fac-6a55b1b0c4e8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 509bd5c4-100e-4982-ba1a-e4eccc5d58fd # Gender
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7bc9bcc-589c-4b9b-bc61-364ab27eea3d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b9826fc5-9f26-43a7-a627-f336c2936d74 # Flag own vehicle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 71703254-6b5e-43f5-bd90-76ca8be9f7ee
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 36cbad23-1b7e-486b-9467-bad15e1d0952 # Related Blog Post
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c38497de-5fa5-48d1-989c-5fe7b8407ccd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e7aed0e8-a5ac-45c1-9f54-942bd630b588 # LanguageSpoken
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a93484df-fd1a-4e59-8325-a7224217439c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 52e559fe-2524-4d45-91c8-7aefd69d07b4 # Hours
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fbd7d479-7cd4-4a7e-99b0-455513fb7c76
            userCondition: null
            warning: null
            width: 100
        name: Details
        uid: 392b32ee-768d-424c-b284-d7862dcb0022
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9c3b9b5a-db9d-4474-a7e0-1be4278b5a4c # Certificate first aid
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7535fac4-f7a5-4774-8a6d-454340f2e0d3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 41dd12e9-b515-42c8-a5a4-90a47c91e18d # Skills community errands
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b58d1f38-3bb6-4961-9650-d74dd37693bf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9db9ce7e-06c3-486a-bde5-5fac7c2d79df # Skills community social
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2dc078b7-51fb-4199-8a45-a41158e64afb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0e3f0840-eff4-4153-8b14-ecfd00ae1cf9 # Skills domestic assistance
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f02592e-7be1-4dca-bc01-081d0bb0e40a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 05342917-7d8b-4fa8-b2e0-94fbc2027682 # Skills food prep
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96ee2e35-6fbd-41d3-8036-b2e8d696ef13
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 63bce363-c266-4576-98a3-ccbab9fac2a2 # Skills shopping
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41139f58-a974-41c5-8f53-1e422ca41e60
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 43ac5ded-0bf8-4bac-98e0-734a7eb1993f # Skills squalor clean
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21a760ca-ab92-4c1f-b74d-37cd50a4dae0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fc3d1269-095f-4de1-947f-41eb486514bb # Skills transport own car
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 154af41d-6d03-4524-8ddb-51e1119a7699
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 62a39f1c-5e5f-4596-b6ac-20a91fbb565e # Skills welfare checks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc07d872-e942-4ec0-8088-d22e4e371709
            userCondition: null
            warning: null
            width: 100
        name: Skills
        uid: a7d6e6b0-fb84-4473-a4a5-5d05f2e1e6ba
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 29e8e555-8f71-46d9-9eea-66b17776ba62 # Certificate three
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8227959d-bc41-4006-8d5f-c5a489cd5bbe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ffdc4d1c-5253-4dfb-99ac-a458facd9bcb # Certificate three dressing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 741f9ff7-2d4c-4a81-bf30-b74455e01ee6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a247bc60-6eeb-4e4b-8522-07b0f8930f34 # Certificate three personal care
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 344295c4-6013-4a9e-ae86-bcb9ee6ac30f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b6af64a8-a5c3-4add-ae6f-7d9cad48df16 # Certificate three sleep over
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6efe3ce9-1547-4e47-9f77-d592120fbbc7
            userCondition: null
            warning: null
            width: 100
        name: 'Cert 3'
        uid: 18ce4a69-ab2c-43ae-a6ba-9438b662bbbd
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 61791cee-3a48-4422-80f3-f382be6c4c7c # Certificate four
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54b92eec-2bb3-4636-b13d-a53d58b8918a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d635e6be-f7d6-424a-a754-b654fda2aff9 # Certificate four dressing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f1a15c6-1bf8-45e9-87e9-f27398a1cfac
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 62045d7b-6c2a-4e78-b89d-e4c49272b77b # Certficate four respite
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72ce6d54-7c3e-444c-be89-99f42637d7b9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0c940699-abbc-4394-86bb-7a1bdfa34c53 # Certificate four sleep over
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6aa73779-bfcb-465a-9567-65ad3344fad0
            userCondition: null
            warning: null
            width: 100
        name: 'Cert 4'
        uid: a259b9ce-a5d9-4846-a494-32f4e1d8e0a1
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: aabee949-1952-48bd-9739-0b3d81923382 # Data drives licence
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27155134-814c-493c-a78c-1767f27320d1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4b6f5c27-bd70-4c60-a950-57c33b333561 # Data police check
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fdb37715-9d5c-4a06-a31e-083b13bcecc1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d0c105c6-1be5-49f3-bba3-8c86ec5f32b4 # Data work with children
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d00ab91-8594-470f-8e0f-2f4a0d7f0070
            userCondition: null
            warning: null
            width: 100
        name: Data
        uid: e3f8ee2f-a7b9-4d02-96ef-7ac658d9e623
        userCondition: null
handle: worker
hasTitleField: true
name: Worker
section: 3e1051a2-12ef-44a2-a5d4-17c675b92c46 # Workers
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
