columnSuffix: qksdqghq
contentColumnType: boolean
fieldGroup: 6d3cda15-81bb-47f4-8e93-9da4f97bf59a # Worker
handle: certificateThreeDressing
instructions: null
name: 'Certificate three dressing'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
