columnSuffix: iqqdcekf
contentColumnType: string
fieldGroup: c9caa7b1-6e38-40ce-9e7b-2fb4bf84a335 # Footer
handle: contactEmail
instructions: null
name: 'Contact Email'
searchable: false
settings:
  placeholder: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
