columnSuffix: sxntqlfu
contentColumnType: char(7)
fieldGroup: 6d4c9dba-9566-43f0-a739-a4f26cc431a9 # Home Hero Banner
handle: h3TextColour
instructions: null
name: 'H3 Text Colour'
searchable: false
settings:
  defaultColor: '#1f7b76'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
