columnSuffix: gbluofyd
contentColumnType: char(7)
fieldGroup: c13bba3b-5701-4f74-b0d6-91e06e282c54 # Header
handle: headerStripBannerBgColour
instructions: null
name: 'Header Strip Banner Background Colour'
searchable: false
settings:
  defaultColor: '#e92b2b'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
