columnSuffix: zklmouff
contentColumnType: text
fieldGroup: c13bba3b-5701-4f74-b0d6-91e06e282c54 # Header
handle: lookingForCare
instructions: null
name: 'Looking For Care'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
