columnSuffix: null
contentColumnType: string
fieldGroup: a85eb049-52b5-441c-958f-e27190b3f0ee # Common
handle: matrix
instructions: null
name: Matrix
searchable: false
settings:
  contentTable: '{{%matrixcontent_matrix}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
