columnSuffix: null
contentColumnType: string
fieldGroup: 6d3cda15-81bb-47f4-8e93-9da4f97bf59a # Worker
handle: photo
instructions: null
name: photo
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:da8cb600-809b-4511-8a8d-3d83d127f66f' # Workers
  defaultUploadLocationSubpath: '{slug}'
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:da8cb600-809b-4511-8a8d-3d83d127f66f' # Workers
  restrictedLocationSubpath: '{slug}'
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:da8cb600-809b-4511-8a8d-3d83d127f66f' # Workers
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
