columnSuffix: qvgrwsyq
contentColumnType: string(6)
fieldGroup: 6d4c9dba-9566-43f0-a739-a4f26cc431a9 # Home Hero Banner
handle: textAlignment
instructions: null
name: 'Text Alignment'
searchable: false
settings:
  columnType: null
  options:
    -
      __assoc__:
        -
          - label
          - Left
        -
          - value
          - left
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Center
        -
          - value
          - center
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Right
        -
          - value
          - right
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
