dateModified: 1701330323
elementSources:
  craft\elements\Asset:
    -
      defaultSort:
        - dateCreated
        - desc
      disabled: false
      key: 'volume:b24eb4b9-6b88-48e2-ac68-648c31f9be66' # Images
      tableAttributes:
        - filename
        - size
        - dateModified
        - link
      type: native
    -
      key: 'folder:cb056e90-2862-4709-a165-542b7b404080'
      type: native
    -
      defaultSort:
        - dateCreated
        - desc
      disabled: false
      key: 'volume:da8cb600-809b-4511-8a8d-3d83d127f66f' # Workers Photo
      tableAttributes:
        - filename
        - size
        - dateModified
        - link
      type: native
  craft\elements\Entry:
    -
      key: '*'
      type: native
    -
      key: singles
      type: native
    -
      heading: Channels
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:3e1051a2-12ef-44a2-a5d4-17c675b92c46' # Workers
      tableAttributes:
        - postDate
        - expiryDate
        - link
        - 'field:ffdc4d1c-5253-4dfb-99ac-a458facd9bcb' # Certificate three dressing
      type: native
    -
      heading: Structures
      type: heading
    -
      key: 'section:17b9af61-551c-42e6-b1ce-4b5d2bf45d74' # Blog Posts
      type: native
    -
      key: 'section:b90c37e6-c4f9-471a-8a79-a3c5ddb40a77' # Matrix Section
      type: native
email:
  fromEmail: stuart@x2network.net
  fromName: Ausdone
  transportType: craft\mail\transportadapters\Sendmail
fs:
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/images'
    type: craft\fs\Local
    url: '@web/images'
meta:
  __names__:
    0b0cab67-d09f-4537-8f25-e2d3eb67217e: 'Bottom Logo' # Bottom Logo
    0b0537c3-696b-4277-8ca6-d9e5a21842df: 'Work For Us Apply Text' # Work For Us Apply Text
    00b4ba89-d7ae-46dd-afbd-8a7a94698bdd: 'Work For Us Point One' # Work For Us Point One
    0c940699-abbc-4394-86bb-7a1bdfa34c53: 'Certificate four sleep over' # Certificate four sleep over
    0d7b7175-a585-4fc4-ba24-47add337e4b8: 'Header Strip Banner Background Colour' # Header Strip Banner Background Colour
    0e3f0840-eff4-4153-8b14-ecfd00ae1cf9: 'Skills domestic assistance' # Skills domestic assistance
    0fe2ef5b-7203-47f8-a9aa-0d6371086e45: tag # tag
    1cd59306-3a97-4446-8369-3d467bcdcab1: 'Address country' # Address country
    1d494a6d-9319-4979-87bb-cedf6f862d06: 'Header Strip Banner Text Colour' # Header Strip Banner Text Colour
    2a35ff7e-6f11-4d9c-a258-363086087a61: Archive # Archive
    2d603167-bb52-4b6d-bf07-b350fadb5663: 'Work For Us Point Four' # Work For Us Point Four
    3ab23732-50b1-4f83-b2e0-71fc5b7bf706: Homepage # Homepage
    3d808769-8107-46df-8874-b0c44ad0a246: Homepage # Homepage
    3e1051a2-12ef-44a2-a5d4-17c675b92c46: Workers # Workers
    3f7dfdfa-b803-4947-b21d-4c152cebd1d1: 'H1 Heading' # H1 Heading
    4a18d76c-3511-4c77-8bea-dbfc0289ef18: 'Description of Care Needed' # Description of Care Needed
    4b6f5c27-bd70-4c60-a950-57c33b333561: 'Data police check' # Data police check
    4f449cb9-09d1-4eb0-bcaf-05a0df165b79: Worker # Worker
    5a2c72c6-d960-4c8d-bf6b-2efebc4313bc: 'Flag active' # Flag active
    5aa1d213-da34-4374-b427-0e6b6c1c4093: 'Name of Requester' # Name of Requester
    5f284340-be3f-49a6-b18e-2bbbc297349d: 'Background Image' # Background Image
    6d3cda15-81bb-47f4-8e93-9da4f97bf59a: Worker # Worker
    6d4c9dba-9566-43f0-a739-a4f26cc431a9: 'Home Hero Banner' # Home Hero Banner
    8bd9f2dd-2bc3-4775-8e94-8cb9e2975cab: Ausdone # Ausdone
    8f54334c-d895-4acb-9356-c254a323bbba: website_blurb # website_blurb
    9c2a17e8-dfae-42bd-a54a-f8e60a086dd2: 'Looking For Work' # Looking For Work
    9c3b9b5a-db9d-4474-a7e0-1be4278b5a4c: 'Certificate first aid' # Certificate first aid
    9d935aa3-ad3e-419e-9c49-065d900f351d: 'Subscribe Blurb' # Subscribe Blurb
    9db9ce7e-06c3-486a-bde5-5fac7c2d79df: 'Skills community social' # Skills community social
    13f45510-7742-4453-a66d-32b723a73bc1: 'Text Alignment' # Text Alignment
    15ee4a1e-53cf-40c3-b14a-a4a00a6a43ef: 'product tags' # product tags
    17b9af61-551c-42e6-b1ce-4b5d2bf45d74: 'Blog Posts' # Blog Posts
    20a04498-465d-42e1-96e1-fa040f064a38: 'Name first' # Name first
    21dc67de-a521-4df1-b30d-358dca6de497: 'Top Logo' # Top Logo
    29e8e555-8f71-46d9-9eea-66b17776ba62: 'Certificate three' # Certificate three
    36cbad23-1b7e-486b-9467-bad15e1d0952: 'Related Blog Post' # Related Blog Post
    41dd12e9-b515-42c8-a5a4-90a47c91e18d: 'Skills community errands' # Skills community errands
    43ac5ded-0bf8-4bac-98e0-734a7eb1993f: 'Skills squalor clean' # Skills squalor clean
    52e559fe-2524-4d45-91c8-7aefd69d07b4: Hours # Hours
    55d143e4-529d-4b33-8631-bddd24e03f12: 'Preferred Language' # Preferred Language
    57a90e0a-4d56-4f15-af92-29ce394c63f0: 'Preferred Gender' # Preferred Gender
    62a39f1c-5e5f-4596-b6ac-20a91fbb565e: 'Skills welfare checks' # Skills welfare checks
    63bce363-c266-4576-98a3-ccbab9fac2a2: 'Skills shopping' # Skills shopping
    76bbde13-e3fd-4a51-8ab2-db4bb0f7c043: 'Name Full' # Name Full
    90cb4561-3a22-484b-bf00-6fbe1832b3a7: 'Contact Email' # Contact Email
    91eda38b-77c5-4277-a644-64ed213a1d47: 'Carer Request' # Carer Request
    94f12f0a-8bfc-4664-b90f-26859d58663c: 'Address postcode' # Address postcode
    98e483a4-5695-48d4-b7f6-230a34dac991: 'Contact Heading' # Contact Heading
    161a6acc-afa0-433b-8025-6acc2264700c: 'Looking For Care' # Looking For Care
    245dd33b-36ba-4899-ba9a-98e124d63870: url2 # url2
    353eb006-c423-4de6-a624-407556dfc671: 'Work For Us Point Two' # Work For Us Point Two
    420c15bc-18bb-4933-8b47-694b99a37cb6: 'Subscribe Privacy Text' # Subscribe Privacy Text
    432d5465-eb64-499b-a874-86c84d5e1290: 'Address line 1' # Address line 1
    509bd5c4-100e-4982-ba1a-e4eccc5d58fd: Gender # Gender
    523b90ff-4ad6-4738-bb9a-21f596f1d8e6: photo # photo
    0722dc22-0b8d-4f90-b741-fee98901b5f6: 'Footer NDIS Logo' # Footer NDIS Logo
    790eaaef-3cfc-47e0-8044-5a3bab104d9b: 'Preferred Date ' # Preferred Date 
    0807e9f7-09b8-43cd-8470-a0f65eaf2baa: 'Address state' # Address state
    7626caeb-665b-4c56-9c87-b4a3f17b0a22: 'Extra Details' # Extra Details
    7664e65c-c618-44aa-9940-910b2af26a5d: 'Header Strip Banner Text' # Header Strip Banner Text
    9654f065-6bca-4c2a-925a-10ba8808da44: 'Phone Number of Requester' # Phone Number of Requester
    41940fba-349c-479b-9bc8-91a243d32a3c: 'H3 Text Colour' # H3 Text Colour
    52327a96-1c32-4610-afaf-c0fe3ca4cb13: New # New
    61791cee-3a48-4422-80f3-f382be6c4c7c: 'Certificate four' # Certificate four
    62045d7b-6c2a-4e78-b89d-e4c49272b77b: 'Certficate four respite' # Certficate four respite
    75903ba9-227c-4d7e-99aa-7f584aa8200c: 'Worker ID' # Worker ID
    91478a49-fa1b-487c-b375-8ad5d94445e9: 'Address of Person' # Address of Person
    93945c5e-9742-4713-8ae1-b10d9c689ca1: 'Header Stip Banner Icon' # Header Stip Banner Icon
    610888e4-a1ea-4d98-acea-1a20d0e0f0d2: Archive # Archive
    05342917-7d8b-4fa8-b2e0-94fbc2027682: 'Skills food prep' # Skills food prep
    42902358-2279-4962-a323-bf1c5261c94d: 'Footer Main Logo' # Footer Main Logo
    85710837-3005-4b34-a9d1-2f83a6e12c63: 'Contact Form' # Contact Form
    a0e35ad9-1dbc-41f1-b262-37998a5ebf53: text # text
    a85eb049-52b5-441c-958f-e27190b3f0ee: Common # Common
    a247bc60-6eeb-4e4b-8522-07b0f8930f34: 'Certificate three personal care' # Certificate three personal care
    aabee949-1952-48bd-9739-0b3d81923382: 'Data drives licence' # Data drives licence
    b6af64a8-a5c3-4add-ae6f-7d9cad48df16: 'Certificate three sleep over' # Certificate three sleep over
    b7b3fa8f-eb96-4e9b-8e20-e83f660148ce: Default # Default
    b14ef9af-c1eb-4982-bf2c-19eea88c291b: 'Contact Address' # Contact Address
    b21e8675-fc63-4b2e-b48d-16eb726f815a: 'Home Hero Banner' # Home Hero Banner
    b24eb4b9-6b88-48e2-ac68-648c31f9be66: Images # Images
    b51d9d86-2b0a-4190-bec1-c98257042834: 'H3 Text' # H3 Text
    b90c37e6-c4f9-471a-8a79-a3c5ddb40a77: 'Matrix Section' # Matrix Section
    b776ceed-90fc-4ec5-b204-6d414157c00d: 'Address suburb' # Address suburb
    b9826fc5-9f26-43a7-a627-f336c2936d74: 'Flag own vehicle' # Flag own vehicle
    ba42f171-44c9-42a0-ab21-710fafeb6b0d: 'Email of Requester' # Email of Requester
    bae20859-015c-43bd-95d0-63c67edb6c28: 'Subscribe Email Text' # Subscribe Email Text
    bdf27aa4-ad8c-401f-bad7-a103bd2b7309: 'Home Hero Banner' # Home Hero Banner
    be8c0e12-0ed4-424f-a76f-ee2aa48a5a7b: Ausdone # Ausdone
    c018e54d-63e6-484a-84f2-b32743462803: firstBlock # firstBlock
    c9caa7b1-6e38-40ce-9e7b-2fb4bf84a335: Footer # Footer
    c13bba3b-5701-4f74-b0d6-91e06e282c54: Header # Header
    c28af183-86b2-49d2-92f9-fd6d75e26aa6: 'Address line 2' # Address line 2
    ce5be0ea-9c46-4233-a9b4-da8b5c64bdb1: 'Subscribe Heading' # Subscribe Heading
    d0c105c6-1be5-49f3-bba3-8c86ec5f32b4: 'Data work with children' # Data work with children
    d4d39b94-b2cc-44f3-a2a6-46bc57760270: 'Work For Us Heading' # Work For Us Heading
    d55b8f1b-c721-47d5-907a-a5b3b4f8c6b8: 'H1 Heading Text Colour' # H1 Heading Text Colour
    d635e6be-f7d6-424a-a754-b654fda2aff9: 'Certificate four dressing' # Certificate four dressing
    d5339bf0-0c3b-4e06-a372-13a219e9f891: 'Main Logo' # Main Logo
    da8cb600-809b-4511-8a8d-3d83d127f66f: 'Workers Photo' # Workers Photo
    dbf3edd5-28da-4614-84d3-0841fbb8252b: 'Worker Name' # Worker Name
    dddb2e53-4226-484e-a0b1-64f52e1c7ef3: 'Preferred Timeframe' # Preferred Timeframe
    e7aed0e8-a5ac-45c1-9f54-942bd630b588: LanguageSpoken # LanguageSpoken
    e8398172-dfa8-4b66-88d7-90e5fb4c5fca: photo # photo
    eb32cbf9-8c3b-4bc5-b478-7efe71705091: Matrix # Matrix
    ec49d8e4-c97b-4932-b960-3c88ab509450: 'Work For Us Text' # Work For Us Text
    ed8fb51e-8e5a-4b70-8553-1aea5ad5cd3a: 'Homepage title' # Homepage title
    ef4e1ba1-c95f-46e9-940a-e046b78ab2ab: 'Skills Required' # Skills Required
    ef824d75-9a0a-43de-be25-c00539b33591: 'Name of Person' # Name of Person
    f08e2dae-9a71-443f-a31f-f1f5bc704665: Default # Default
    f1a82881-d178-401f-8f09-4355aa408c55: Footer # Footer
    f27954b2-b55d-4fc8-820b-48b482177845: 'Work For Us Point Three' # Work For Us Point Three
    f93491e1-e91d-494b-9aa5-633b7526af58: 'Footer Blurb' # Footer Blurb
    f7390550-7c31-47e0-ac43-41b97e72f1a7: 'Name last' # Name last
    fc3d1269-095f-4de1-947f-41eb486514bb: 'Skills transport own car' # Skills transport own car
    fe0be946-d064-4229-9fdc-9ae4b5a115f1: 'Hours monday morning' # Hours monday morning
    fe02199d-2db9-4e35-a301-aa8949880f16: Header # Header
    ffdc4d1c-5253-4dfb-99ac-a458facd9bcb: 'Certificate three dressing' # Certificate three dressing
plugins:
  _my-feedme:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-css:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 5.1.0.0
  filemaker:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      authURL: 'https://fm.x2network.net/fmi/data/v2/databases/ausdone/sessions'
      pass: 'A4R67YYi&r$'
      user: fmapi
  formie:
    edition: standard
    enabled: true
    licenseKey: LOCASVI2AVQ4DWYOYNE7Y91R
    schemaVersion: 2.0.11
  image-toolbox:
    edition: lite
    enabled: true
    schemaVersion: 1.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: FFS5FQJIW4UZL1Z2PWT39C7C
    schemaVersion: 2.0.7
    settings:
      bypassProjectConfig: false
      pluginName: Navigation
  webhooks:
    edition: standard
    enabled: true
    schemaVersion: 2.4.0
system:
  edition: pro
  live: $DEV_MODE
  name: Ausdone
  retryDuration: null
  schemaVersion: 4.5.3.0
  timeZone: Australia/Sydney
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
