dateModified: 1706496258
elementSources:
  craft\elements\Asset:
    -
      defaultSort:
        - dateCreated
        - desc
      disabled: false
      key: 'volume:b24eb4b9-6b88-48e2-ac68-648c31f9be66' # Images
      tableAttributes:
        - filename
        - size
        - dateModified
        - link
      type: native
    -
      key: 'folder:cb056e90-2862-4709-a165-542b7b404080'
      type: native
    -
      defaultSort:
        - dateCreated
        - desc
      disabled: false
      key: 'volume:da8cb600-809b-4511-8a8d-3d83d127f66f' # Workers
      tableAttributes:
        - filename
        - size
        - dateModified
        - link
      type: native
  craft\elements\Entry:
    -
      key: '*'
      type: native
    -
      key: singles
      type: native
    -
      heading: Channels
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:3e1051a2-12ef-44a2-a5d4-17c675b92c46' # Worker single
      tableAttributes:
        - postDate
        - expiryDate
        - link
        - 'field:ffdc4d1c-5253-4dfb-99ac-a458facd9bcb'
      type: native
    -
      heading: Structures
      type: heading
    -
      key: 'section:17b9af61-551c-42e6-b1ce-4b5d2bf45d74' # Blog Posts
      type: native
    -
      key: 'section:b90c37e6-c4f9-471a-8a79-a3c5ddb40a77'
      type: native
email:
  fromEmail: stuart@ausdone.com.au
  fromName: Ausdone
  replyToEmail: stuart@ausdone.com.au
  template: ''
  transportSettings:
    host: mail.ausdone.com.au
    password: A4B89xc$1234
    port: '465'
    useAuthentication: '1'
    username: stuart@ausdone.com.au
  transportType: craft\mail\transportadapters\Smtp
fs:
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/images'
    type: craft\fs\Local
    url: '@web/images'
  workers:
    hasUrls: true
    name: workers
    settings:
      path: '@webroot/images/workers'
    type: craft\fs\Local
    url: '@web/images/workers'
meta:
  __names__:
    0b0cab67-d09f-4537-8f25-e2d3eb67217e: 'Bottom Logo' # Bottom Logo
    0b0537c3-696b-4277-8ca6-d9e5a21842df: 'Work For Us Apply Text' # Work For Us Apply Text
    00b4ba89-d7ae-46dd-afbd-8a7a94698bdd: 'Work For Us Point One' # Work For Us Point One
    0fe2ef5b-7203-47f8-a9aa-0d6371086e45: tag # tag
    1cd59306-3a97-4446-8369-3d467bcdcab1: 'Address country' # Address country
    1d23eb08-1a31-4c73-b90f-275166f49dba: 'Button color' # Button color
    1e24cdd8-9955-4209-8ac1-0f100d6182ed: 'Qualifications level' # Qualifications level
    2a35ff7e-6f11-4d9c-a258-363086087a61: Archive # Archive
    2d603167-bb52-4b6d-bf07-b350fadb5663: 'Work For Us Point Four' # Work For Us Point Four
    03a7be27-5e51-4b89-ae9a-ba2807acb6aa: Image # Image
    3ab23732-50b1-4f83-b2e0-71fc5b7bf706: Homepage # Homepage
    3af6f30d-ebb6-479e-853d-0ff3f15a27c0: 'Contact info' # Contact info
    3b0d5b83-e769-4cc2-8380-036b6f8d5927: 'Contact form with info' # Contact form with info
    3b1ff493-fb9c-4afd-91ae-539038f1fc8e: New # New
    3d808769-8107-46df-8874-b0c44ad0a246: Homepage # Homepage
    3e1051a2-12ef-44a2-a5d4-17c675b92c46: 'Worker single' # Worker single
    03f0ec46-e9cf-4bbb-b4ed-62838ee3f9b7: 'Text top' # Text top
    3f7dfdfa-b803-4947-b21d-4c152cebd1d1: 'H1 Heading' # H1 Heading
    4a18d76c-3511-4c77-8bea-dbfc0289ef18: 'Description of Care Needed' # Description of Care Needed
    4c67e41f-ec16-414e-9cf6-a4dbbd242d6b: Default # Default
    04d7a610-a4fd-4563-a910-0f069dc05c49: 'Worker drivers license switch' # Worker drivers license switch
    4e712fb7-9a3a-4f48-ad04-43dcde743c6d: 'Buttons menu' # Buttons menu
    4f449cb9-09d1-4eb0-bcaf-05a0df165b79: Worker # Worker
    5a898a8e-0b51-479e-a204-99fe7b0d28c9: Gender # Gender
    5aa1d213-da34-4374-b427-0e6b6c1c4093: 'Name of Requester' # Name of Requester
    5bbc7488-0193-4112-a953-fd0904c521a5: 'Content block' # Content block
    5bd60f97-146a-4c95-b6e2-ae04b8635108: 'Text content' # Text content
    5f284340-be3f-49a6-b18e-2bbbc297349d: 'Background Image' # Background Image
    6d3cda15-81bb-47f4-8e93-9da4f97bf59a: Worker # Worker
    6d4c9dba-9566-43f0-a739-a4f26cc431a9: 'Home Hero Banner' # Home Hero Banner
    7ab68556-9843-4796-a998-c854caf30678: 'Public Schema' # Public Schema
    8bd9f2dd-2bc3-4775-8e94-8cb9e2975cab: English # English
    8f54334c-d895-4acb-9356-c254a323bbba: 'Website Blurb' # Website Blurb
    9d935aa3-ad3e-419e-9c49-065d900f351d: 'Subscribe Blurb' # Subscribe Blurb
    13f45510-7742-4453-a66d-32b723a73bc1: 'Text Alignment' # Text Alignment
    15ee4a1e-53cf-40c3-b14a-a4a00a6a43ef: 'product tags' # product tags
    16c2d93d-6e37-43e0-be79-e2f56de37a45: test # test
    17b9af61-551c-42e6-b1ce-4b5d2bf45d74: 'Blog Posts' # Blog Posts
    20a04498-465d-42e1-96e1-fa040f064a38: 'Name first' # Name first
    21dc67de-a521-4df1-b30d-358dca6de497: 'Top Logo' # Top Logo
    22b7cdae-c78f-4612-a57c-04b2d0e2877b: 'Footer column 1 text' # Footer column 1 text
    34b180d7-9048-4b31-b82b-d0aaa65273c7: 'Single column' # Single column
    36cbad23-1b7e-486b-9467-bad15e1d0952: 'Related Blog Post' # Related Blog Post
    38d9e3d2-288c-483f-b4f7-430951adfad5: 'Common sections' # Common sections
    52e559fe-2524-4d45-91c8-7aefd69d07b4: Hours # Hours
    55d143e4-529d-4b33-8631-bddd24e03f12: 'Preferred Language' # Preferred Language
    57a90e0a-4d56-4f15-af92-29ce394c63f0: 'Preferred Gender' # Preferred Gender
    76bbde13-e3fd-4a51-8ab2-db4bb0f7c043: 'Name Full' # Name Full
    83f09f1b-6aea-47e8-96d1-b0df3812eef7: 'Workers list' # Workers list
    83f37988-a937-4515-a664-bf3310ae25cc: Columns # Columns
    90cb4561-3a22-484b-bf00-6fbe1832b3a7: 'Contact Email' # Contact Email
    91eda38b-77c5-4277-a644-64ed213a1d47: 'Carer Request' # Carer Request
    93f5e82e-df77-4abe-b36e-b2fce45ebf07: 'Contact info' # Contact info
    94f12f0a-8bfc-4664-b90f-26859d58663c: 'Address postcode' # Address postcode
    98e483a4-5695-48d4-b7f6-230a34dac991: 'Contact Heading' # Contact Heading
    245dd33b-36ba-4899-ba9a-98e124d63870: url2 # url2
    353eb006-c423-4de6-a624-407556dfc671: 'Work For Us Point Two' # Work For Us Point Two
    392e8eb3-17c6-4747-9339-357a5e072e5e: Banner # Banner
    420c15bc-18bb-4933-8b47-694b99a37cb6: 'Subscribe Privacy Text' # Subscribe Privacy Text
    432d5465-eb64-499b-a874-86c84d5e1290: 'Address line 1' # Address line 1
    520e6436-6d9e-417c-9227-d98545d630f5: 'Contact phones' # Contact phones
    523b90ff-4ad6-4738-bb9a-21f596f1d8e6: 'Cover image' # Cover image
    0722dc22-0b8d-4f90-b741-fee98901b5f6: 'NDIS Logo' # NDIS Logo
    790eaaef-3cfc-47e0-8044-5a3bab104d9b: 'Preferred Date ' # Preferred Date 
    0807e9f7-09b8-43cd-8470-a0f65eaf2baa: 'Address state' # Address state
    3156c5ca-b9a4-44b9-a244-a7c36a2cc5dc: 'Image background and right text' # Image background and right text
    3517f381-06b5-4318-870a-c4ca56886b4a: 'Content blocks' # Content blocks
    7626caeb-665b-4c56-9c87-b4a3f17b0a22: 'Extra Details' # Extra Details
    9654f065-6bca-4c2a-925a-10ba8808da44: 'Phone Number of Requester' # Phone Number of Requester
    11372e41-b6d0-4f56-8ebc-dc3f30b43e28: 'Worker Cert IV switch' # Worker Cert IV switch
    22245ecd-bb11-42c1-8061-421d98515a56: 'Header override' # Header override
    40423bd5-222b-4e05-9db8-d6d3fb9a56e7: 'Worker - formal training text' # Worker - formal training text
    41940fba-349c-479b-9bc8-91a243d32a3c: 'H3 Text Colour' # H3 Text Colour
    52327a96-1c32-4610-afaf-c0fe3ca4cb13: New # New
    58855ca8-c890-4430-96a6-640139fb7d24: 'Worker - experience text' # Worker - experience text
    75903ba9-227c-4d7e-99aa-7f584aa8200c: 'Worker ID' # Worker ID
    91478a49-fa1b-487c-b375-8ad5d94445e9: 'Address of Person' # Address of Person
    610888e4-a1ea-4d98-acea-1a20d0e0f0d2: Archive # Archive
    0694993b-82ea-43ae-bf79-eabba2ebb7b6: 'Worker - used for search' # Worker - used for search
    785684d6-40af-4d67-831f-fa10c69e55e5: 'Show title' # Show title
    5562724a-a38e-4c11-9331-772c139a98b7: 'Work for us apply entry' # Work for us apply entry
    6845970a-1845-422e-9277-812a0cbc7cea: 'Text content' # Text content
    7227699c-4373-4051-96d7-70ba93dc7b0e: 'Formie form' # Formie form
    85710837-3005-4b34-a9d1-2f83a6e12c63: 'Contact Form' # Contact Form
    94209415-2a6c-469d-a232-ca8b86975199: 'Worker - services offered text' # Worker - services offered text
    a0ad271a-2c9f-4db0-901f-23c8a1509909: 'Formie form' # Formie form
    a0e35ad9-1dbc-41f1-b262-37998a5ebf53: text # text
    a85eb049-52b5-441c-958f-e27190b3f0ee: Common # Common
    a711ddbd-6947-48bd-b820-f0f52d8b265c: 'Worker first aid switch' # Worker first aid switch
    a92387e1-3705-4abc-93e2-fd324239faf9: 'Contact form common with info - common' # Contact form common with info - common
    a9009397-7048-4e62-9892-c4f7fdae8a66: 'Main Menu' # Main Menu
    ab5e9ab5-f6af-43a6-8d7c-605a3c6eccb2: 'Worker meal prep switch' # Worker meal prep switch
    ae275637-0ef8-4ef1-8ab2-d5e253fd00d5: 'Book me entry' # Book me entry
    b2ba8bd4-447f-4e91-8ad8-2d934c2ef942: 'Contact me entry' # Contact me entry
    b4a0f245-6040-43c8-b4f3-236d895fd240: 'Image gallery' # Image gallery
    b14ef9af-c1eb-4982-bf2c-19eea88c291b: 'Contact Address' # Contact Address
    b24eb4b9-6b88-48e2-ac68-648c31f9be66: Images # Images
    b28cb340-f1af-41ee-8f72-9eb37daccb9b: 'Job Request' # Job Request
    b37e2109-a2e2-4e1a-a4ec-2f0f5fefb082: Header # Header
    b51d9d86-2b0a-4190-bec1-c98257042834: 'H3 Text' # H3 Text
    b776ceed-90fc-4ec5-b204-6d414157c00d: 'Address suburb' # Address suburb
    ba42f171-44c9-42a0-ab21-710fafeb6b0d: 'Email of Requester' # Email of Requester
    bafdfaf4-e163-4a83-bea9-988abff4a504: 'Text bottom' # Text bottom
    bbae794d-848e-45ea-ab84-0edc0c470817: 'Workers Search' # Workers Search
    be8c0e12-0ed4-424f-a76f-ee2aa48a5a7b: Ausdone # Ausdone
    c018e54d-63e6-484a-84f2-b32743462803: firstBlock # firstBlock
    c6b8aa74-a475-4b02-a483-13901b461115: Chinese # Chinese
    c9caa7b1-6e38-40ce-9e7b-2fb4bf84a335: Footer # Footer
    c13bba3b-5701-4f74-b0d6-91e06e282c54: Header # Header
    c28af183-86b2-49d2-92f9-fd6d75e26aa6: 'Address line 2' # Address line 2
    cb98f577-eaa6-420c-8901-7e7211711913: Simple # Simple
    ce5be0ea-9c46-4233-a9b4-da8b5c64bdb1: 'Subscribe Heading' # Subscribe Heading
    d4d39b94-b2cc-44f3-a2a6-46bc57760270: 'Work For Us Heading' # Work For Us Heading
    d48c2ecd-a976-4601-b1f5-b6a25d867987: 'Common contact section' # Common contact section
    d55b8f1b-c721-47d5-907a-a5b3b4f8c6b8: 'H1 Heading Text Colour' # H1 Heading Text Colour
    d5339bf0-0c3b-4e06-a372-13a219e9f891: 'Main Logo' # Main Logo
    da8cb600-809b-4511-8a8d-3d83d127f66f: Workers # Workers
    dbf3edd5-28da-4614-84d3-0841fbb8252b: 'Worker Name' # Worker Name
    dddb2e53-4226-484e-a0b1-64f52e1c7ef3: 'Preferred Timeframe' # Preferred Timeframe
    deb3f93a-e5fa-42e6-bff2-6ebfc4596f16: 'Workers Search' # Workers Search
    e7aed0e8-a5ac-45c1-9f54-942bd630b588: LanguageSpoken # LanguageSpoken
    e58f1760-17c2-4aea-bd7a-c3eb8d9ede32: 'Worker services' # Worker services
    e1716f4e-7b80-4caa-a01a-f0c206f5b15f: 'Worker description' # Worker description
    e98687ed-1a9c-422b-8b0e-aa4404a526bb: 'Header banner' # Header banner
    e8398172-dfa8-4b66-88d7-90e5fb4c5fca: photo # photo
    eb32cbf9-8c3b-4bc5-b478-7efe71705091: Matrix # Matrix
    ec49d8e4-c97b-4932-b960-3c88ab509450: 'Work For Us Text' # Work For Us Text
    ed8fb51e-8e5a-4b70-8553-1aea5ad5cd3a: 'Homepage title' # Homepage title
    ef4e1ba1-c95f-46e9-940a-e046b78ab2ab: 'Skills Required' # Skills Required
    ef824d75-9a0a-43de-be25-c00539b33591: 'Name of Person' # Name of Person
    f08e2dae-9a71-443f-a31f-f1f5bc704665: Default # Default
    f1a82881-d178-401f-8f09-4355aa408c55: Footer # Footer
    f117cdaa-9ffc-49fe-8e8f-549d03101b15: 'Forms settings' # Forms settings
    f27954b2-b55d-4fc8-820b-48b482177845: 'Work For Us Point Three' # Work For Us Point Three
    f7390550-7c31-47e0-ac43-41b97e72f1a7: 'Name last' # Name last
    f8399451-3080-4611-868d-7bb5d2133d08: 'Content page' # Content page
    fe0be946-d064-4229-9fdc-9ae4b5a115f1: 'Hours monday morning' # Hours monday morning
    fe02199d-2db9-4e35-a301-aa8949880f16: Header # Header
plugins:
  _my-feedme:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-css:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 5.1.0.0
  feedme-filemaker:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      authURL: 'https://fm.x2network.net/fmi/data/v2/databases/ausdone/sessions'
      pass: 'A4R67YYi&r$'
      user: fmapi
  field-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  filemaker:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  formie:
    edition: standard
    enabled: true
    licenseKey: LOCASVI2AVQ4DWYOYNE7Y91R
    schemaVersion: 2.0.11
  formie-filemaker:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  image-toolbox:
    edition: lite
    enabled: true
    schemaVersion: 1.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: FFS5FQJIW4UZL1Z2PWT39C7C
    schemaVersion: 2.0.7
    settings:
      bypassProjectConfig: false
      pluginName: Navigation
  neo:
    edition: standard
    enabled: true
    licenseKey: 8G5AN55O1IX23STXJRFVE2UJ
    schemaVersion: 4.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  static-file-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  webhooks:
    edition: standard
    enabled: true
    schemaVersion: 2.4.0
  webhooks-filemaker:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: $DEV_MODE
  name: Ausdone
  retryDuration: null
  schemaVersion: 4.5.3.0
  timeZone: Australia/Sydney
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
