fieldLayouts:
  b3c2ea3f-0454-4b04-b99b-b569170a145c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d5339bf0-0c3b-4e06-a372-13a219e9f891 # Main Logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e6ebe25-5a8a-4d62-98ec-657be9f72eff
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 22b7cdae-c78f-4612-a57c-04b2d0e2877b # Footer column 1 text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a4f3d3bb-ae8f-4f50-a69c-cadf7c3f9e5f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0722dc22-0b8d-4f90-b741-fee98901b5f6 # NDIS Logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57b033eb-b559-4f56-9e66-c4edeec537ef
            userCondition: null
            warning: null
            width: 100
        name: 'Column One'
        uid: 9c5fc000-e395-421b-aa9c-f46977c92a7a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 98e483a4-5695-48d4-b7f6-230a34dac991 # Contact Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a4d1908-1d89-4e96-a8a7-00556bf571c1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b14ef9af-c1eb-4982-bf2c-19eea88c291b # Contact Address
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3403ebd-6368-4999-8614-09e1c40f0dff
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 90cb4561-3a22-484b-bf00-6fbe1832b3a7 # Contact Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e79740f1-2f4e-4660-a144-2b1d13fb4146
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9654f065-6bca-4c2a-925a-10ba8808da44 # Phone Number of Requester
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cce745c6-6492-44e5-b7e9-53c84391e21a
            userCondition: null
            warning: null
            width: 100
        name: 'Column Two'
        uid: a21b2bb4-71a5-406c-89e3-1ecfe9afd8e5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d4d39b94-b2cc-44f3-a2a6-46bc57760270 # Work For Us Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2508bfb6-6d0f-44fe-b259-3da30d5295ec
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ec49d8e4-c97b-4932-b960-3c88ab509450 # Work For Us Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37dce299-919e-458e-b0fd-39f470f20e17
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 00b4ba89-d7ae-46dd-afbd-8a7a94698bdd # Work For Us Point One
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd9742f8-906d-4df0-a777-59b59186d709
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 353eb006-c423-4de6-a624-407556dfc671 # Work For Us Point Two
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4b8df65-2ca6-4685-ba16-36d485056019
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f27954b2-b55d-4fc8-820b-48b482177845 # Work For Us Point Three
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3976cec-727b-48f5-b01e-597beb55bdac
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2d603167-bb52-4b6d-bf07-b350fadb5663 # Work For Us Point Four
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2da8259d-269e-4755-89e7-39f126bfcc63
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0b0537c3-696b-4277-8ca6-d9e5a21842df # Work For Us Apply Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 32823797-10ab-4d92-98a8-ba131aea8405
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5562724a-a38e-4c11-9331-772c139a98b7 # Work for us apply entry
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72e6e18a-5231-4cd5-8c05-cd37bfbd02ea
            userCondition: null
            warning: null
            width: 100
        name: 'Column Three'
        uid: ffd90f76-0d73-4dde-9b7f-811681b042fe
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ce5be0ea-9c46-4233-a9b4-da8b5c64bdb1 # Subscribe Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e001a644-31fe-4bf6-bc8b-e3e691f1b1c2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9d935aa3-ad3e-419e-9c49-065d900f351d # Subscribe Blurb
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4effb75a-d831-4d2b-82e9-616435962d32
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7227699c-4373-4051-96d7-70ba93dc7b0e # Formie form
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 257f232a-9f3b-42de-88a8-8ba3ac8972b5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 420c15bc-18bb-4933-8b47-694b99a37cb6 # Subscribe Privacy Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8c012204-85f3-4365-a7e5-fba2e97c31a7
            userCondition: null
            warning: null
            width: 100
        name: 'Column Four'
        uid: f193269d-4e49-4f34-b5d0-d38d3e29c25a
        userCondition: null
handle: footer
name: Footer
sortOrder: 2
