defaultPlacement: end
enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  8bd9f2dd-2bc3-4775-8e94-8cb9e2975cab: # English
    enabledByDefault: true
    hasUrls: true
    template: _pages/home/home.twig
    uriFormat: __home__
type: single
