defaultPlacement: end
enableVersioning: true
handle: matrixSection
name: 'Matrix Section'
propagationMethod: all
siteSettings:
  8bd9f2dd-2bc3-4775-8e94-8cb9e2975cab: # Ausdone
    enabledByDefault: true
    hasUrls: true
    template: matrix-section/_entry
    uriFormat: 'matrix-section/{slug}'
structure:
  maxLevels: 3
  uid: fb6b2fb7-5794-4634-a50a-5ab18214e290
type: structure
