defaultPlacement: end
enableVersioning: true
handle: workers
name: Workers
propagationMethod: all
siteSettings:
  8bd9f2dd-2bc3-4775-8e94-8cb9e2975cab: # English
    enabledByDefault: true
    hasUrls: true
    template: b-layouts/default.twig
    uriFormat: 'worker/{slug}'
  c6b8aa74-a475-4b02-a483-13901b461115: # Chinese
    enabledByDefault: true
    hasUrls: true
    template: b-layouts/default.twig
    uriFormat: 'worker/{slug}'
type: channel
