defaultPlacement: end
enableVersioning: true
handle: workersSearch
name: 'Workers Search'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  8bd9f2dd-2bc3-4775-8e94-8cb9e2975cab: # English
    enabledByDefault: true
    hasUrls: true
    template: _pages/worker-search/worker-search.twig
    uriFormat: workers-search
  c6b8aa74-a475-4b02-a483-13901b461115: # Chinese
    enabledByDefault: true
    hasUrls: true
    template: workers-search/_entry
    uriFormat: workers-search
type: single
